25-10-2016_08:45:19  -  main from rfaRunner.py:  It is working, right?
25-10-2016_08:45:19  -  testLoggerInsideRunner() from rfaRunner.py:  logging a lot of nums
25-10-2016_08:45:19  -  testLoggerInsideRunner() from rfaRunner.py:  0
25-10-2016_08:45:19  -  testLoggerInsideRunner() from rfaRunner.py:  1
25-10-2016_08:45:19  -  testLoggerInsideRunner() from rfaRunner.py:  2
25-10-2016_08:45:19  -  testLoggerInsideRunner() from rfaRunner.py:  3
25-10-2016_08:45:19  -  testLoggerInsideRunner() from rfaRunner.py:  4
25-10-2016_08:45:19  -  testLoggerInsideRunner() from rfaRunner.py:  5
25-10-2016_08:45:19  -  testLoggerInsideRunner() from rfaRunner.py:  6
25-10-2016_08:45:19  -  testLoggerInsideRunner() from rfaRunner.py:  7
25-10-2016_08:45:19  -  testLoggerInsideRunner() from rfaRunner.py:  8
25-10-2016_08:45:19  -  testLoggerInsideRunner() from rfaRunner.py:  9
25-10-2016_08:45:24  -  testLoggerOutsideRunner() from subRunner.py:  Appends to the same file after a long sleep!
25-10-2016_08:45:39  -  testLoggerOutsideRunner() from subRunner.py:  Will be one file for the whole program run
